config/routes.rb
Rails.application.routes.draw do
  

  resources :custom_vitals
  root 'pages#home'

  devise_for 	:users, 
  						:path => '', 
  						:path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'},
  						:controllers => {:omniauth_callbacks => 'omniauth_callbacks',
  														 :registrations => 'registrations'
  														}

  resources :users, only: [:show]
  resources :practices
  resources :photos
  resources :reports
  resources :bloodsugars
  resources :bloodpressures
  resources :temperatures
  resources :weights
  resources :heartbeats
  resources :practices do
    resources :appointments, only: [:create]
  end
  resources :conversations, only: [:index,:create] do
    resources :messages, only: [:index,:create]
  end
  
  resources :practices do
    resources :reviews, only: [:create,:destroy]
  end
  
  get '/vital' => 'pages#vital'
  
  get '/preload' => 'appointments#preload'
  get '/preview' => 'appointments#preview'

  get '/your_trips' => 'appointments#your_trips'
  get '/your_appointments' => 'appointments#your_appointments'

  post '/notify' => 'appointments#notify'
  post '/your_trips' => 'appointments#your_trips'

  get 'check_date_time' => 'appointments#check_date_time'
  
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :user
  belongs_to :practice
end

app/models/bloodpressure.rb
class Bloodpressure < ActiveRecord::Base
  belongs_to :user
  validates :date,:systolic,:dystolic,presence:true
end

app/models/bloodsugar.rb
class Bloodsugar < ActiveRecord::Base
  belongs_to :user
  validates :date,:fasting,:nonfasting,presence:true
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
	belongs_to :sender, foreign_key: :sender_id, class_name: 'User'
	belongs_to :recipient, foreign_key: :recipient_id, class_name: 'User'

	has_many :messages, dependent: :destroy

	validates_uniqueness_of :sender_id, scope: :recipient_id

	scope :involving, -> (user) do
		where("conversations.sender_id = ? OR conversations.recipient_id = ?", user.id, user.id)
	end

	scope :between, -> (sender_id, recipient_id) do
		where("(conversations.sender_id = ? AND conversations.recipient_id = ?) OR (conversations.sender_id = ? AND conversations.recipient_id = ?)", 
					sender_id, recipient_id, recipient_id, sender_id)
	end

end

app/models/custom_vital.rb
class CustomVital < ActiveRecord::Base
  belongs_to :user
end

app/models/heartbeat.rb
class Heartbeat < ActiveRecord::Base
  belongs_to :user
  validates :date,:count,presence:true
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :content, :conversation_id, :user_id

  def message_time
  	created_at.strftime("%v")
  end

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :practice

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/practice.rb
class Practice < ActiveRecord::Base
  belongs_to :user
  has_many :photos
  has_many :appointments
  has_many :reviews
  
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  
  validates :dr_first_name, presence: true
  validates :dr_last_name,  presence: true
  validates :experience,    presence: true
  validates :speciality,    presence: true
  validates :address,       presence: true 
  validates :professional_statement,presence: true
  validates :is_insurance,  presence: true 

 def average_rating
    reviews.count == 0 ? 0 : reviews.average(:star).round(2)
 end

  def self.search(search)
    where("speciality like ? OR zip_code like ?", "%#{search}%", "%#{search}%")
  end
end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :user
  mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
  validates :name, presence: true # Make sure the owner's name is present.
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :practice
  belongs_to :user
end

app/models/temperature.rb
class Temperature < ActiveRecord::Base
  belongs_to :user
  validates :date,:temperature, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :omniauthable

  validates :fullname, presence: true, length: {maximum: 50}
  
  has_many :practices
  has_many :appointments
  has_many :reviews
  has_many :reports
  has_many :bloodpressures
  has_many :bloodsugars
  has_many :heartbeats
  has_many :temperatures
  has_many :weights

  def self.from_omniauth(auth)
  	where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.fullname = auth.info.name
        user.provider = auth.provider
        user.uid = auth.uid
        user.email = auth.info.email
        user.image = auth.info.image
        user.password = Devise.friendly_token[0,20]
      end
  end
  
  def google_client
     client = Google::Apis::FitnessV1::FitnessService.new
     @g_data = client.users.dataSources.list
     
  end

end

app/models/weight.rb
class Weight < ActiveRecord::Base
  belongs_to :user
  validates :date,:weight,presence:true
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	@practices = Practice.all.page(params[:page]).per(15)
		if params[:search]
			@practices = Practice.search(params[:search]).order("created_at DESC")
		else
			@practices = Practice.all.order("created_at DESC")
		end
  end

  def vital
  	if(params["format"])
  		@user  = User.find(params["format"])
  	else
  		@user = current_user
  	end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	def show
		@user = User.find(params[:id])
		@practices = @user.practices
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def avatar_url(user)
		gravatar_id = Digest::MD5::hexdigest(user.email).downcase 
		if user.image
			user.image
		else
			"https://woodzon.com/image/data/profile_icon.png"
		end
	end
end

app/helpers/custom_vitals_helper.rb
module CustomVitalsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/practices_helper.rb
module PracticesHelper
end

app/views/shared/_devisemes.html.erb
<% unless resource.errors.empty? %>
	<script type="text/javascript">
		<% resource.errors.full_messages.each do |msg| %>
			toastr.error('<%= msg %>')
		<% end %>
	</script>
<% end %>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
	<script type="text/javascript">
		<% flash.each do |f| %>
			<% type = f[0].to_s.gsub('alert','error').gsub('notice','info') %>
			toastr['<%= type %>']('<%= f[1] %>')
		<% end %>
	</script>
<% end %>

app/views/shared/_navbar.html.erb
<!-- Static navbar -->
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
      <a class="navbar-brand" href="https://patientportalfinal-shreya19888.c9users.io">Patient Portal</a>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        
        <% if(!user_signed_in?) %>
          <li><%= link_to "Log In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% else %>
        
          <% if current_user.practices.count == 0 %>
            <li>
              <%= link_to reports_path do %>
              <i class="fa fa-file" aria-hidden="true"></i> Reports
              <% end %>
            </li>
            <li>
              <%= link_to vital_path do %>
              <i class="fa fa-line-chart" aria-hidden="true"></i> Vitals
              <% end %>
            </li>
          <% end %>
          <li><%= link_to "Your Past Appointments", your_trips_path, class: "sidebar-link" %></li>
           
            
        <% end %>
        <li>
          <%= link_to conversations_path do %>
            <i class="fa fa-envelope-o"></i> Messages
            
          <% end %>
        </li>

        <li>
          <%= link_to new_practice_path do %>
          <i class="fa fa-user-md fa-2x"></i> List Your Practice
          <% end %>
        </li>

        <% if(user_signed_in?) %>
          <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <%= image_tag avatar_url(current_user), class: "img-circle avatar-small" %>&nbsp;
              <%= current_user.fullname %>
              <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
        <%end%>
      </ul>
      
    </div><!--/.nav-collapse -->
  </div>
</nav>