config/routes.rb
Rails.application.routes.draw do
  

  resources :custom_vitals
  root 'pages#home'

  devise_for 	:users, 
  						:path => '', 
  						:path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'},
  						:controllers => {:omniauth_callbacks => 'omniauth_callbacks',
  														 :registrations => 'registrations'
  														}

  resources :users, only: [:show]
  resources :practices
  resources :photos
  resources :reports
  resources :bloodsugars
  resources :bloodpressures
  resources :temperatures
  resources :weights
  resources :heartbeats
  resources :practices do
    resources :appointments, only: [:create]
  end
  resources :conversations, only: [:index,:create] do
    resources :messages, only: [:index,:create]
  end
  
  resources :practices do
    resources :reviews, only: [:create,:destroy]
  end
  
  get '/vital' => 'pages#vital'
  
  get '/preload' => 'appointments#preload'
  get '/preview' => 'appointments#preview'

  get '/your_trips' => 'appointments#your_trips'
  get '/your_appointments' => 'appointments#your_appointments'

  post '/notify' => 'appointments#notify'
  post '/your_trips' => 'appointments#your_trips'

  get 'check_date_time' => 'appointments#check_date_time'
  
end

app/models/practice.rb
class Practice < ActiveRecord::Base
  belongs_to :user
  has_many :photos
  has_many :appointments
  has_many :reviews
  
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  
  validates :dr_first_name, presence: true
  validates :dr_last_name,  presence: true
  validates :experience,    presence: true
  validates :speciality,    presence: true
  validates :address,       presence: true 
  validates :professional_statement,presence: true
  validates :is_insurance,  presence: true 

 def average_rating
    reviews.count == 0 ? 0 : reviews.average(:star).round(2)
 end

  def self.search(search)
    where("speciality like ? OR zip_code like ?", "%#{search}%", "%#{search}%")
  end
end

app/controllers/practices_controller.rb
class PracticesController < ApplicationController
  before_action :set_practice,only:[:show,:edit,:update]
  before_action :authenticate_user!,except: [:show]
  def index
    @practices = current_user.practices
  end

  def show
    @photos = @practice.photos
    @booked = Appointment.where("practice_id = ? AND user_id = ?", @practice.id, current_user.id).present? if current_user

    @reviews = @practice.reviews
    @hasReview = @reviews.find_by(user_id: current_user.id) if current_user
  end

  def new
    @practice = current_user.practices.build
  end

  def create
     @practice = current_user.practices.build(practice_params)
     if @practice.save
       if params[:images] 
         params[:images].each do |image|
           @practice.photos.create(image: image)
           end
       end
           @photos = @practice.photos
           redirect_to edit_practice_path(@practice), notice: "Saved..."
        else
      render :new
     end
  end

  def edit
   if current_user.id == @practice.user.id
      @photos = @practice.photos
    else
      redirect_to root_path, notice: "You don't have permission."
   end
  end

  def update
    if @practice.update(practice_params)

      if params[:images] 
        params[:images].each do |image|
          @practice.photos.create(image: image)
        end
      end

      redirect_to edit_practice_path(@practice), notice: "Updated..."
    else
      render :edit
    end
  end
  
  private
  def set_practice
    @practice = Practice.find(params[:id])
  end
  
  def practice_params
    params.require(:practice).permit(:dr_first_name,:dr_last_name,:experience,:speciality,:address,:professional_statement,:is_insurance,:active,:insurance,:zip_code,:price)
  end
end

app/helpers/practices_helper.rb
module PracticesHelper
end

app/views/practices/_form.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		List Your Practice
	</div>
	<div class="panel-body">
		<div class="container">
			
			<%= form_for @practice, :html => { multipart: true } do |f| %>
				<div class="row">
					<div class="form-group">
						<label>First Name</label>
						<%= f.text_field :dr_first_name, placeholder: "Please Enter your First Name", class: "form-control" %>
					</div>
				</div>

				<div class="row">
					<div class="form-group">
						<label>Last Name</label>
						<%= f.text_field :dr_last_name, placeholder: "Please Enter your Last Name", class: "form-control" %>
					</div>
				</div>
				<div class="row">
					<div class="form-group">
					   <label>Speciality</label>
							<%= f.select :speciality, [["Allergist","Allergist"],["Anaesthesiologist","Anaesthesiologist"],["Audiologist","Audiologist"],["Anaesthesiologist","Anaesthesiologist"],["Cardiologist","Cardiologist"],["Chiropractor","Chiropractor"],["Dentist","Dentist"],["Diagnostician","Diagnostician"],["Dermatologist","Dermatologist"],["Endocrinologist","Endocrinologist"],["Epidemiologist","Epidemiologist"],["General Physician","General Physician"],["Gastroenterologist","Gastroenterologist"],["Geriatrician","Geriatrician"],["Hematologist","Hematologist"],["Hepatologist","Hepatologist"],["Immunologist","Immunologist"],["Intensivist","Intensivist"],["Internal Medicine Specialist","Internal Medicine Specialist"],["Microbiologist","Microbiologist"],["Medical Geneticist","Medical Geneticist"],["Neonatologist","Neonatologist"],["Neurologist","Neurologist"],["Neurosurgeon","Neurosurgeon"],["Obstetrician/Gynecologist (OB/GYN)","Obstetrician/Gynecologist (OB/GYN)"],["Oncologist","Oncologist"],["Ophthalmologist","Ophthalmologist"],["Orthopedic Surgeon / Orthopedist","Orthopedic Surgeon / Orthopedist"],["ENT(Otolaryngologist)","ENT(Otolaryngologist)"],["Parasitologist","Parasitologist"],["Palliative care specialist","Palliative care specialist"],["Perinatologist","Perinatologist"],["Periodontist","Periodontist"],["Physiotherapist","Physiotherapist"],["Podiatrist / Chiropodist","Podiatrist / Chiropodist"],["Pediatrician","Pediatrician"],["Psychiatrist","Psychiatrist"],["Pulmonologist","Pulmonologist"],["Radiologist","Radiologist"],["Rheumatologist","Rheumatologist"],["Sleep Doctor","Sleep Doctor"],["Surgeon","Surgeon"],["Urologist","Urologist"]], id: "speciality",prompt: "Select...", class: "form-control" %>
					</div>
				</div>
				
				<div class="row">
				    <div class="col-md-4">
						<div class="form-group">
							<%= f.check_box :is_insurance %> Accepts Insurance
						</div>
				    </div>	
				<div class="row">
					<div class="form-group">
						<%= f.check_box :active %> Active
					</div>
				</div>
				    
					<div class="col-md-4 select">
						<div class="form-group">
							<label>Preferred Insurance</label>
							<%= f.select :insurance, [["Aetna","Aetna"], ["Blue Cross Blue Shield","Blue Cross Blue Shield"], ["Cigna","Cigna"],["Davis Vision","Davis Vision"],["Keystone First","Keystone First"],["Medicare","Medicare"],["UnitedHealthCare","UnitedHealthCare"],["Others","Others"]], id: "insurance", prompt: "Select...", class: "form-control" %>
						</div>
					</div>
				        <div class="col-md-4 select">
					        <div class="form-group">
						        <label>Years of Experience</label>
							    <%= f.select :experience, [["1",1], ["2",2], ["3",3], ["4",4], ["5",5], ["6",6], ["7",7], ["8",8], ["9",9], ["10",10], ["11",11], ["12",12], ["13",13], ["14",14], ["15+",15], ["20+",20], ["25+",25], ["30+",30], ["35+",35], ["40+",40]], id: "experience",prompt: "Select...", class: "form-control" %>
					        </div>
				        </div>
				</div>
					<div class="row">
					<div class="col-md-4">
						<div class="form-group">
							<label>Consultation Charges</label>
							<div class="input-group">
								<div class="input-group-addon">$</div>
								<%= f.text_field :price, placeholder: "eg. $100", class: "form-control" %>
							</div>	
						</div>
					</div>
				</div>
			    
			    <div class="row">
					<div class="form-group">
						<label>Professional Statement</label>
						<%= f.text_area :professional_statement, rows: 15, placeholder: "Tell us about Yourself", class: "form-control" %>
					</div>
				</div>
				<div class="row">
					<div class="form-group">
						<label>Address</label>
						<%= f.text_field :address, placeholder: "What is your address?", class: "form-control" %>
					</div>
				</div>
				<div class="row">
						<div class="form-group">
							<label>Zip Code</label>
							<div class="input-group">
								<%= f.text_field :zip_code, placeholder: "47201", class: "form-group" %>
							</div>	
						</div>
				</div>
				
				<div class="row">
					<div class="col-md-4">
						<div class="form-group">							
							<span class="btn btn-default btn-file">
							    <i class="fa fa-cloud-upload fa-lg"></i> Upload Photos 
							    <%= file_field_tag "images[]", type: :file, multiple: true %>
							</span>
						</div>		
					</div>
				</div>
				
				<div id="photos"><%= render 'photos/list' %></div>
				
				<div class="actions">
					<%= f.submit "Save", class: "btn btn-primary" %>
				</div>

			<% end %>

		</div>
	</div>
</div>

app/views/practices/create.html.erb
<h1>Practices#create</h1>
<p>Find me in app/views/practices/create.html.erb</p>

app/views/practices/edit.html.erb
<%= render 'form' %>

app/views/practices/index.html.erb
<div class="row">
	<div class="col-md-3">
		<ul class="sidebar-list">
			<% if current_user.practices.count == 1%>
			<li class="sidebar-item"><%= link_to "Your Practices", practices_path, class: "sidebar-link" %></li>
			<li class="sidebar-item"><%= link_to "Your Patients", your_appointments_path, class: "sidebar-link" %></li>
			<% end %>
			<% if current_user.practices == 0%>
				<li class="sidebar-item"><%= link_to "Past Doctor's appointments", your_trips_path, class: "sidebar-link" %></li>
			<% end %>
		</ul>
	</div>
	<div class="col-md-9">
		<div class="panel panel-default">
			<div class="panel-heading">
				Listings
			</div>
			<div class="panel-body">
				
				<% @practices.each do |practice| %>
					<div class="row">
						<div class="col-md-2">
							<%= image_tag practice.photos[0].image.url(:thumb) if practice.photos.length > 0 %>
						</div>		
						<div class="col-md-7">
							<h4 style="display:inline-block;">Dr.<%= practice.dr_first_name %></h4>
							<h4 style="display:inline-block;"><%= practice.dr_last_name %></h4>
							<h5>Speciality:<%= practice.speciality %></h5>
							<h5><%= practice.experience %> Years of Practice</h5>
							<h6>Address: <%= practice.address %></h6>
							<h6><%= practice.zip_code %></h6>
							
						</div>		
						<div class="col-md-3 right">
							<%= link_to "Update", edit_practice_path(practice), class: "btn btn-primary" %>
						</div>		
					</div>
					<hr>
				<% end %>

			</div>
		</div>
	</div>
</div>

app/views/practices/new.html.erb
<%= render 'form' %>

app/views/practices/show.html.erb
<div class="panel panel-default">
	<div class="panel-body">
		<!-- Main Info -->
		<div class="row">
			<div class="col-md-8">
				<div class="row">
					<div class="col-md-3 text-center">
						<%= link_to user_path(@practice.user) do %>
						<%= image_tag avatar_url(@practice.user), class: "img-circle avatar-large" %><br><br>
						Dr.<%= @practice.dr_first_name %>
						<% end %>
					</div>

					<div class="col-md-9">
					    <h4 style="display:inline-block;">Dr.<%= @practice.dr_first_name %></h4>
						<h4 style="display:inline-block;"><%= @practice.dr_last_name %></h4>
						<h4>Specialization: <%= @practice.speciality %></h4>
						<h4><%= @practice.experience %> Years of Practice</h4>
						<h5>Address: <%= @practice.address %></h5>
						<h5><%= @practice.zip_code %></h5>
					</div>
				</div>
			</div>

		</div>

		<!-- About -->
		<div class="row">
			<div class="col-md-12">
				<h4>Know Your Doctor</h4>
				<p><%= @practice.professional_statement %></p>
			</div>
		</div>

		<!-- Amenities -->
		<div class="row">
			<div class="col-md-2">
				<p>Insurance Information</p>
			</div>
			<div class="col-md-10">
				<div class="row">
					<div class="col-md-6">
							<li class="<%= 'text-line-through' if !@practice.is_insurance %>">Insurance</li>
					</div>
					<h5>Preferred Insurance: <%= @practice.insurance %></h5>
				</div>
			</div>
		</div>
		
			<div class="col-md-4">
				<!-- Appointments form -->	
				<%= render 'appointments/form' %>
			</div>
		</div>   					

		<!-- Carousel -->
		<div class="row">
			<div class="col-md-10 col-md-offset-1">
				<div id="myCarousel" class="carousel slide" data-ride="carousel">
				  
					<% if @photos %>
						<!-- Indicators -->
				    <ol class="carousel-indicators">
							<% @photos.each do |photo| %>
								<li data-target="#myCarousel" data-slide-to="<%= photo.id %>"></li>
							<% end %>	
						</ol>				
					<% end %>     

				  <div class="carousel-inner" role="listbox">
				    <% if @photos %>				
							<% @photos.each do |photo| %>
								<div class="item <%= 'active' if photo.id == @photos[0].id %>">          
				          <%= image_tag photo.image.url() %>
				        </div>
							<% end %>	
						<% end %>
				  </div>

				  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
				    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
				    <span class="sr-only">Previous</span>
				  </a>
				  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
				    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
				    <span class="sr-only">Next</span>
				  </a>
				</div>
			</div>
		</div>

		<br>
		<hr>
		
		<!-- Reviews -->
		<div class="row">
			<div class="col-md-12">
				<h3>Reviews <span id="average_rating"></span> (<%= @reviews.count %>)</h3>
				<div class="container">
					<div>
						<%= render 'reviews/form' if @booked && !@hasReview %>
					</div>
					<div>
						<%= render 'reviews/list' %>
					</div>
				</div>
			</div>
		</div>
		
		<!-- Google Map -->
		<div class="row">
			<div class="col-md-12">
				
				<div id="map"></div>

				<style>
		      #map {
		        width: 100%;
		        height: 400px;
		      }
		    </style>
		    
		<!-- Other doctor's Nearby -->
		<h4>Other Doctor's Nearby</h4>
		<div class="row">
			<% for practice in @practice.nearbys(10) %>
				
				<div class="col-md-4">
					<div class="panel panel-default">
						<div class="panel-body">
							<%= link_to practice.speciality, practice %><br>
							(<%= practice.distance.round(2) %> miles away)
						</div>
					</div>
				</div>

			<% end %>
		</div>

		    <script src="https://maps.googleapis.com/maps/api/js"></script>
		    <script>
		      function initialize() {
		        var mapCanvas = document.getElementById('map');
		        var mapOptions = {
		          center: new google.maps.LatLng(<%= @practice.latitude %>, <%= @practice.longitude %>),
		          zoom: 14,
		          mapTypeId: google.maps.MapTypeId.ROADMAP
		        }
		        var map = new google.maps.Map(mapCanvas, mapOptions);
		        var marker = new google.maps.Marker({
		        	position: new google.maps.LatLng(<%= @practice.latitude %>, <%= @practice.longitude %>),
		        	title: "PatientPortal" 
		        });
		        marker.setMap(map);
		      }
		      google.maps.event.addDomListener(window, 'load', initialize);
		    </script>


			</div>
		</div>



	</div>
</div>
<script>
	$('#average_rating').raty({
		path: '/assets',
		readOnly: true,
		score: <%= @practice.average_rating %>
	});
</script>
	
<script type="text/javascript">
  $(document).ready(function() {
    $('.carousel').carousel({
      interval: 1200
    })
  });
</script>

app/views/practices/update.html.erb
<h1>Practices#update</h1>
<p>Find me in app/views/practices/update.html.erb</p>