config/routes.rb
Rails.application.routes.draw do
  

  resources :custom_vitals
  root 'pages#home'

  devise_for 	:users, 
  						:path => '', 
  						:path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'},
  						:controllers => {:omniauth_callbacks => 'omniauth_callbacks',
  														 :registrations => 'registrations'
  														}

  resources :users, only: [:show]
  resources :practices
  resources :photos
  resources :reports
  resources :bloodsugars
  resources :bloodpressures
  resources :temperatures
  resources :weights
  resources :heartbeats
  resources :practices do
    resources :appointments, only: [:create]
  end
  resources :conversations, only: [:index,:create] do
    resources :messages, only: [:index,:create]
  end
  
  resources :practices do
    resources :reviews, only: [:create,:destroy]
  end
  
  get '/vital' => 'pages#vital'
  
  get '/preload' => 'appointments#preload'
  get '/preview' => 'appointments#preview'

  get '/your_trips' => 'appointments#your_trips'
  get '/your_appointments' => 'appointments#your_appointments'

  post '/notify' => 'appointments#notify'
  post '/your_trips' => 'appointments#your_trips'

  get 'check_date_time' => 'appointments#check_date_time'
  
end

app/models/bloodpressure.rb
class Bloodpressure < ActiveRecord::Base
  belongs_to :user
  validates :date,:systolic,:dystolic,presence:true
end

app/controllers/bloodpressures_controller.rb
class BloodpressuresController < ApplicationController
  before_action :authenticate_user!
  before_action :set_bloodpressure, only: [:show, :edit, :update, :destroy]

  # GET /bloodpressures
  # GET /bloodpressures.json
  def index
    @bloodpressures = current_user.bloodpressures.page(params[:page]).per(3)
  end

  # GET /bloodpressures/1
  # GET /bloodpressures/1.json
  def show
    @bloodpressures = Bloodpressure.find_by(user_id: current_user.id) if current_user
  end

  # GET /bloodpressures/new
  def new
    @bloodpressure = current_user.bloodpressures.build
  end

  # GET /bloodpressures/1/edit
  def edit
  end

  # POST /bloodpressures
  # POST /bloodpressures.json
  def create
    @bloodpressure = current_user.bloodpressures.build(bloodpressure_params)

    respond_to do |format|
      if @bloodpressure.save
        format.html { redirect_to @bloodpressure, notice: 'Bloodpressure Record Created' }
        format.json { render :show, status: :created, location: @bloodpressure }
      else
        format.html { render :new }
        format.json { render json: @bloodpressure.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bloodpressures/1
  # PATCH/PUT /bloodpressures/1.json
  def update
    respond_to do |format|
      if @bloodpressure.update(bloodpressure_params)
        format.html { redirect_to @bloodpressure, notice: 'Bloodpressure Record Updated.' }
        format.json { render :show, status: :ok, location: @bloodpressure }
      else
        format.html { render :edit }
        format.json { render json: @bloodpressure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bloodpressures/1
  # DELETE /bloodpressures/1.json
  def destroy
    if current_user.id == @bloodpressure.user.id
      @bloodpressure.destroy
      respond_to do |format|
        format.html { redirect_to bloodpressures_url, notice: 'Bloodpressure Record Deleted' }
        format.json { head :no_content }
        end
    else
    redirect_to root_path, notice: "You don't have permission."
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bloodpressure
      @bloodpressure = Bloodpressure.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bloodpressure_params
      params.require(:bloodpressure).permit(:date, :systolic, :dystolic, :measuredd)
    end
end

app/views/bloodpressures/_form.html.erb
<%= form_for(@bloodpressure) do |f| %>
  <% if @bloodpressure.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bloodpressure.errors.count, "error") %> prohibited this bloodpressure from being saved:</h2>

      <ul>
      <% @bloodpressure.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date,class: 'form-control-label' %><br>
    <%= f.date_select :date,class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :systolic,class: 'form-control-label' %><br>
    <%= f.text_field :systolic,class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :dystolic,class: 'form-control-label' %><br>
    <%= f.text_field :dystolic,class: 'form-control' %>
  </div>
  
    <div class="form-group">
      <label>Measuring Unit</label>
      <%= f.select :measuredd, [ 'mmHg' ], :prompt => 'Select Unit' %>
      </div>
	<br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bloodpressures/edit.html.erb
<h1>Edit Existing Bloodpressure Record</h1>

<%= render 'form' %>

<%= link_to 'Show', @bloodpressure %> |
<%= link_to 'Back', bloodpressures_path %>

app/views/bloodpressures/index.html.erb
<% if !flash[:notice].blank? %>
  <div class="alert alert-info">
  <%= flash[:notice] %>
  </div>
<% end %>
<br />

<h1>Bloodpressure Report</h1>
<%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
<div style="border:2px solid black">
<%= line_chart [
  {name: "Systolic", data: Bloodpressure.where(:user_id => current_user.id).group("date(bloodpressures.date)").average(:systolic)},
  {name: "Dystolic", data: Bloodpressure.where(:user_id => current_user.id).group("date(bloodpressures.date)").average(:dystolic)}
] %>
</div>
<br>

<table class ="table table-striped">
  <thead class ="thead thead-default">
    <tr>
      <th>Date</th>
      <th>Systolic Pressure</th>
      <th>Dystolic Pressure</th>
      <th>Measuring Unit</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bloodpressures.each do |bloodpressure| %>
      <tr>
        <td><%= bloodpressure.date.strftime("%d/%m/%Y") %></td>
        <td><%= bloodpressure.systolic %></td>
        <td><%= bloodpressure.dystolic %></td>
        <td><%= bloodpressure.measuredd %></td>
        <td><%= link_to 'Show', bloodpressure,class: 'btn btn-mini' %></td>
        <td><%= link_to 'Edit', edit_bloodpressure_path(bloodpressure),class: 'btn btn-mini btn-success' %></td>
        <td><%= link_to 'Destroy', bloodpressure, method: :delete,class: 'btn btn-mini btn-danger', data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div id="paginator">
<%= paginate @bloodpressures %>
</div>
<br>


<%= link_to 'New Bloodpressure Record', new_bloodpressure_path,class: "btn btn-secondary"%>

app/views/bloodpressures/new.html.erb
<h1>New Bloodpressure Record</h1>

<%= render 'form' %>

<%= link_to 'Back', bloodpressures_path %>

app/views/bloodpressures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @bloodpressure.date.strftime("%d/%m/%Y") %>
</p>

<p>
  <strong>Systolic:</strong>
  <%= @bloodpressure.systolic %>
</p>

<p>
  <strong>Dystolic:</strong>
  <%= @bloodpressure.dystolic %>
</p>

<p>
  <strong>Measuring Unit:</strong>
  <%= @bloodpressure.measuredd %>
</p>


<%= link_to 'Edit', edit_bloodpressure_path(@bloodpressure) %> |
<%= link_to 'Back', bloodpressures_path %>