config/routes.rb
Rails.application.routes.draw do
  

  resources :custom_vitals
  root 'pages#home'

  devise_for 	:users, 
  						:path => '', 
  						:path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'},
  						:controllers => {:omniauth_callbacks => 'omniauth_callbacks',
  														 :registrations => 'registrations'
  														}

  resources :users, only: [:show]
  resources :practices
  resources :photos
  resources :reports
  resources :bloodsugars
  resources :bloodpressures
  resources :temperatures
  resources :weights
  resources :heartbeats
  resources :practices do
    resources :appointments, only: [:create]
  end
  resources :conversations, only: [:index,:create] do
    resources :messages, only: [:index,:create]
  end
  
  resources :practices do
    resources :reviews, only: [:create,:destroy]
  end
  
  get '/vital' => 'pages#vital'
  
  get '/preload' => 'appointments#preload'
  get '/preview' => 'appointments#preview'

  get '/your_trips' => 'appointments#your_trips'
  get '/your_appointments' => 'appointments#your_appointments'

  post '/notify' => 'appointments#notify'
  post '/your_trips' => 'appointments#your_trips'

  get 'check_date_time' => 'appointments#check_date_time'
  
end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :user
  mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
  validates :name, presence: true # Make sure the owner's name is present.
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /reports
  # GET /reports.json
  def index
    if(params["format"])
      user  = User.find(params["format"])
      if(user)
        @user = user
        @reports = user.reports
      else
        @user = current_user
        @reports = current_user.reports
      end
    else
      @user = current_user
      @reports = current_user.reports
    end
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
    @reports = current_user.reports
  end

  # GET /reports/new
  def new
    @report = current_user.reports.build
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = current_user.reports.build(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    if current_user.id == @report.user.id
      @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  else
    redirect_to root_path, notice: "You don't have permission."
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:name, :attachment)
    end
end

app/views/reports/_form.html.erb
<%= form_for(@report) do |f| %>
  <% if @report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% @report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :attachment %><br>
    <%= f.text_field :attachment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reports/edit.html.erb
<h1>Editing Report</h1>

<%= render 'form' %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<% if !flash[:notice].blank? %>
  <div class="alert alert-info">
  <%= flash[:notice] %>
  </div>
<% end %>
<br />

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Description</th>
      <th>Download Link</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= report.name %></td>
        <td><%= link_to "Download Report", report.attachment_url %></td>
        <td><%= button_to "Delete",  report, method: :delete, class: "btn btn-danger", data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>



<br>

<% if current_user == @user %>
<%= link_to "New Report", new_report_path, class: "btn btn-primary" %>
<% end %>

app/views/reports/new.html.erb
<% if !@report.errors.empty? %>
   <div class = "alert alert-error">
      
      <ul>
         <% @report.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
         <% end %>
      </ul>
      
   </div>
<% end %>

<div class = "well">
   <%= form_for @report, html: { multipart: true } do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.label :attachment %>
      <%= f.file_field :attachment %>
      <%= f.submit "Save", class: "btn btn-primary" %>
   <% end %>
</div>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Report Name:</strong>
  <%= @report.name %>
</p>

<p>
  <strong>Attachment:</strong>
  <%= @report.attachment %>
</p>

<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', reports_path %>